---
title: "RNA-Seq-PANC-1 Project"
author: "Jason A. Rivera"
date: "2026-03-30"
output: html_document
---
```{r}
#Install and load all necessary dependencies to execute RNA-Seq workflow a

#Set the seed for the pipeline
set.seed(8)

#Install Bioconductor and other tools  
install.packages("BiocManager")
BiocManager::install("Biostrings")a
BiocManager::install("tximport")
BiocManager::install("DESeq2")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("biomaRt")
BiocManager::install("apeglm")
install.packages("readr")
install.packages("pheatmap")
install.packages("tidyverse")
install.packages("curl")

#Import necessary libraries
library(ggplot2)
library(dplyr)
library(BiocManager)
library(DESeq2)
library(tximport)
library(org.Hs.eg.db)
library(readr)
library(pheatmap)
library(biomaRt)
library(apeglm)
library(RColorBrewer)
library(tibble)
library(tidyverse)
```

```{r}
#View amount of cores for FastQC use
parallel::detectCores()

#The amount of memory to read these files is intensive, the alternative is to use FastQC for determing quality of sequencing.

#Since processing with Salmon outputs raw counts at the transcription level, convert this to the gene level. 

# Step 1 — Build tx2gene mapping
#k <- keys(org.Hs.eg.db, keytype = "ENSEMBLTRANS")
#tx2gene <- select(org.Hs.eg.db, 
                  #keys = k, 
                  #keytype = "ENSEMBLTRANS", 
                  #columns = "ENSEMBL")

biomart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

tx2gene_full <- getBM(
  attributes = c("ensembl_transcript_id", "ensembl_gene_id"),
  mart = biomart)

# Step 2 — Point to all 6 quant.sf files
files <- c(
  "/Users/jasonrivera/Desktop/sra_data/trimmed/SRR33705621_quant/quant.sf",
  "/Users/jasonrivera/Desktop/sra_data/trimmed/SRR33705622_quant/quant.sf",
  "/Users/jasonrivera/Desktop/sra_data/trimmed/SRR33705623_quant/quant.sf",
  "/Users/jasonrivera/Desktop/sra_data/trimmed/SRR33705624_quant/quant.sf",
  "/Users/jasonrivera/Desktop/sra_data/trimmed/SRR33705625_quant/quant.sf",
  "/Users/jasonrivera/Desktop/sra_data/trimmed/SRR33705626_quant/quant.sf"
)

names(files) <- c(
  "SRR33705621", "SRR33705622", "SRR33705623",
  "SRR33705624", "SRR33705625", "SRR33705626"
)

# Step 3 — Import and collapse to gene level
txi <- tximport(files,
                type = "salmon",
                tx2gene = tx2gene_full,
                ignoreTxVersion = TRUE)  # strips the .1 from ENST IDs

# Step 4 — Check the count matrix
head(txi$counts)
dim(txi$counts)  # should show ~25,000 genes x 6 samples

```

```{r}
#Look at the raw counts of the data, gain a sense of the counts for each sample
View(txi$counts) 

#Construct the meta-dataframe for modeling with DESeq2
samples <- c("SRR33705623", "SRR33705625", "SRR33705626", "SRR33705621", "SRR33705622", "SRR33705624") 
condition <- c("control", "control", "control", "knockdown", "knockdown", "knockdown") 
meta_dataframe <- data.frame(row.names = samples, condition)
meta_dataframe <- meta_dataframe[colnames(txi$counts), ,drop = FALSE]

#Check the order of the txi and the data-frame to see if they are in order for DESeq2.

#Check column order of count matrix
colnames(txi$counts)

#Check row order of metadata
rownames(meta_dataframe)

#For the condition column, convert into factor
meta_dataframe$condition <- factor(meta_dataframe$condition,levels= c("control", "knockdown"))
```

```{r}
#Now that the metadata and count data is in order, it is now possible to construct the DESeq2 object.
dsq_2 <- DESeqDataSetFromTximport(txi = txi, colData = meta_dataframe, design = ~ condition)
dim(counts(dsq_2))

#No Filtering applied since this would remove essential genes for statistical differentiation; necessary to retain all genes for maximum statistical power given limited gene set.

#Lets now normalize the samples, will be using rlog() since there are relatively low samples for this project. 
rlog_dsq2 <- rlog(dsq_2, blind = TRUE)

#After normalizing, extracting is important for downstream visualizations to check for any outliers or inconsistencies for the samples
rlog_mat <- assay(rlog_dsq2)
rlog_cor <- cor(rlog_mat)

#With the normalized counts extracted as a matrix and with correlation scores, proceed with heat-map visualization; save plot as well.
pdf("heatmap_data.pdf", width = 8, height = 6)
heatmap_data <- pheatmap(rlog_cor, annotation_col = meta_dataframe[, "condition", drop = FALSE])
dev.off() 

#Following construction of the heat-map, confirm further results with PCA; save the PCA plot. 
pdf("PCA_plot.pdf", width = 8, height = 6)
plotPCA(rlog_dsq2, intgroup = "condition")
dev.off() 

```

```{r}
#The observations have revealed that are samples are visually different from each other based on the PCA and heat-map plot, appropriate to run DESeq now.
deseq <- DESeq(dsq_2)

#Model has been fitted, view the dispersion relative to the means for each gene in the model
pdf("dispersion_graph.pdf", width = 8, height = 6)
plotDispEsts(deseq) 
dev.off()

#Obtain the results from the modeling with DESeq2
results_dsq <- results(deseq, contrast = c("condition", "knockdown", "control"), alpha = 0.05) 
#use resultsNames() to check naming for DESeq2 model

#Create the plot for MA to show differently expressed genes
pdf("MA_plot_no_shrink.pdf", width = 8, height = 6)
plotMA(results_dsq, ylim = c(-22, 10))
dev.off() 

#The MA plot shows the differently expressed genes as expected, but by applying lfcShrink() (log 2-fold shrinkage) we can shrink the dispersion values. 

#Applying log-2 fold change to the results and plotting shrinked MA plot 
results_dsq_shr <- lfcShrink(deseq, coef = "condition_knockdown_vs_control", type = "apeglm")
pdf("MA_plot_shrink.pdf", width = 8, height = 6)
plotMA(results_dsq_shr, ylim = c(-8, 8))
dev.off() 

```

```{r}
#Concrete evidence has shown that their was difference in expression in the samples so lets now look into detail which genes were most differential expressed. 

#View the columns and summary of the results 
mcols(results_dsq)
summary(results_dsq)

#Extract the normalized counts from the DESeq2
normalized_counts <- counts(deseq, normalized = TRUE)

#Select the color scheme for the heat-map with the normalized values for expression of samples and the significant genes. 
color_heat <- brewer.pal(6, "YlOrRd")

#Remove genes with zero variance across samples
normalized_counts_clean <- normalized_counts[apply(normalized_counts, 1, var) > 0, ]

#Get significant genes
sig_genes <- rownames(results_dsq_shr[which(results_dsq_shr$padj < 0.05), ])

#Subset to significant genes only
sig_norm_counts <- normalized_counts_clean[rownames(normalized_counts_clean) %in% sig_genes, ]

#Construct the heat-map with the normalized values for expression of samples and the significant genes. 
pdf("heatmap_results_expression.pdf", width = 8, height = 6)
pheatmap(sig_norm_counts, 
         color = color_heat, 
         cluster_rows = T, 
         show_rownames = F, 
         annotation_col = meta_dataframe[, "condition", drop = FALSE], 
         scale = "row")
dev.off() 

#Another useful plot providing a global view of the results is the volcano plot. 
results_dsq_all <- as.data.frame(results_dsq) %>%
                    rownames_to_column(var = "ENSGENE") %>%
                    filter(!is.na(padj)) %>%
                    mutate(threshold = padj < 0.05)
ggplot(results_dsq_all)+
  geom_point(aes(x = log2FoldChange, y = -log10(padj), color = threshold)) +
  xlab("log2 Fold Change") +
  ylab("-log10 adjusted p-value") +
  theme(legend.position = "none", 
    plot.title = element_text(size = rel(1.5), hjust = 0.5),
    axis.title = element_text(size = rel(1.25)))
ggsave("Volcano_plot_results.pdf", width = 8, height = 6, dpi = 300)

#left of the origin indicates down-regulation, right up-regulation of significant genes. 

#Reformatting table for ggplot, wide format to long format for top 20 genes.
top20_sig_genes <- as.data.frame(results_dsq_shr) %>%
  rownames_to_column(var = "ENSEMBL") %>%
  filter(padj < 0.05) %>%
  arrange(padj) %>%
  head(20) %>%
  pull(ENSEMBL)

table <- normalized_counts[top20_sig_genes, ] %>%
  as.data.frame() %>%
  rownames_to_column(var = "ENSGENE") %>%
  pivot_longer(cols = starts_with("SRR"), 
               names_to = "sample", 
               values_to = "normalized_counts")

meta_dataframe_col <- meta_dataframe %>% 
  rownames_to_column(var = "sample")
table_join <- left_join(table, meta_dataframe_col, by = "sample")
  
#The project is complete, but lets add annotations for genes that is more informative. 
annotations <- AnnotationDbi::select(org.Hs.eg.db,
  keys = rownames(sig_norm_counts),
  keytype = "ENSEMBL",
  columns = c("SYMBOL", "GENENAME"))

table_join_annotated <- left_join(table_join, 
                                   annotations, 
                                   by = c("ENSGENE" = "ENSEMBL"))

#Visualization of top 20 genes that were differential expressed.
ggplot(table_join_annotated) +
  geom_point(aes(x = SYMBOL, y = normalized_counts, color = condition)) +
  scale_y_log10() +
  xlab("Gene Symbol") +
  ylab("Log10 Normalized Counts") +
  ggtitle("Top 20 Differentially Expressed Genes \n STYK1 Knockdown vs. Control") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(plot.title = element_text(hjust = 0.5))
ggsave("top_20_genes_results.pdf", width = 8, height = 6, dpi = 300)

#Finally, lets convert the DE results list to a csv file.
sig_results_annotated <- as.data.frame(results_dsq_shr) %>%
  rownames_to_column(var = "ENSEMBL") %>%
  filter(padj < 0.05) %>%
  arrange(padj) %>%
  left_join(annotations, by = "ENSEMBL") %>%
  filter(!is.na(SYMBOL))  # removes genes with no annotation

write.csv(sig_results_annotated,
          file = "/Users/jasonrivera/Desktop/DE_sig_results_annotated_STYK1_knockdown.csv",
          row.names = FALSE)

#correct file path to the correct path.

#Info on version for each package
sessionInfo()

```



